### ISSUE TITLE
HealthBox  

### ISSUE THREAD

**Issue by ErikPerzzon** [Tixhyl/eu.renson.healthbox#4]
Hi there,

After the update 1.41 with the latest Homey Pro update the Healthbox 3.0 can’t be found by the app. When I tried to reinstall the app and search for Healtbox 3.0 - no new device is found. 

Best regards,

//Erik

**Comment by Tixhyl** [comment]
Hi Erik,

I've just tried adding my device again and I do see it. 
Can you try searching for your device again and then sending a diagnostics report to me?

Thx for the feedback
Christophe

**Comment by ErikPerzzon** [comment]
Hi Christophe,I will try tomorrow and send the log file.Thanks in advance! Best regardsErik15 juni 2024 kl. 13:39 skrev Christophe ***@***.***>:﻿
Hi Erik,
I've just tried adding my device again and I do see it.
Can you try searching for your device again and then sending a diagnostics report to me?
Thx for the feedback
Christophe

**Comment by ErikPerzzon** [comment]
*Hi Christophe!*

Sorry for the late reply. I have restarted the Renson HealthBox 3.0 and
that seemed to solve my issues. I can now find the unit and add it to Homey
Pro without any issues. The problem was all on my side.

Thanks for a nice app! Keep up the good work.

Best regards,

// Erik



Den lör 15 juni 2024 kl 13:39 skrev Christophe ***@***.***>:

**Comment by Tixhyl** [comment]
Hi Erik,

Perfect, I love issues like these!

Thanks and have a nice day
